name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      NEXT_PUBLIC_PROFILE_PASSWORD:
        description: 'Profile password for deployment'
        required: false
        default: '1234'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        env:
          NODE_ENV: production
          NEXT_PUBLIC_PROFILE_PASSWORD: ${{ github.event.inputs.NEXT_PUBLIC_PROFILE_PASSWORD || '1234' }}
        run: |
          echo "Starting Next.js build..."
          echo "NODE_ENV: $NODE_ENV"
          echo "NEXT_PUBLIC_PROFILE_PASSWORD: $NEXT_PUBLIC_PROFILE_PASSWORD"
          echo "Next.js version:"
          npx next --version
          npm run build
          echo "Build completed. Checking output directory..."
          ls -la
          if [ -d "./out" ]; then
            echo "✅ Output directory exists"
            ls -la ./out
          else
            echo "❌ Output directory not found"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
